apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uu4c7fatp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uu4c7fatp-nodejs 
  name: uu4c7fatp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uu4c7fatp-nodejs 
